# 第三章 
## 在Python 中执行整数和浮点数的数学运算时很简单的。尽管如此，如果你需要执行分数、数组或者是日期和时间的运算的话，就得做更多的工作了。本章集中讨论的就是这些主题。

## 3.1 数字的四舍五入

In [1]:
round(1.23,1)

1.2

In [2]:
round(1.27,1)

1.3

In [3]:
x = 1.23456

In [4]:
'Value of x is {:0.3f}'.format(x)

'Value of x is 1.235'

## 3.2 执行精确的浮点数运算

In [5]:
a = 4.2
b = 3.1
c = a+b

In [6]:
c

7.300000000000001

In [7]:
c == a+b

True

In [8]:
c == 7.3

False

In [14]:
a = Decimal('4.2')
b = Decimal('3.1')
from decimal import Decimal
(a+b) == Decimal('7.3')

True

## 3.3 数字的格式化输出

格式化输出单个数字的时候，可以使用内置的format() 函数，比如：

In [15]:
x = 1234.56789

In [17]:
format(x,'^20')

'     1234.56789     '

In [18]:
format(x,',')

'1,234.56789'

In [19]:
format(x,'e')

'1.234568e+03'

## 3.4 二八十六进制整数

In [20]:
x = 1234

In [21]:
bin(x)

'0b10011010010'

In [22]:
oct(x)

'0o2322'

In [23]:
hex(x)

'0x4d2'

In [24]:
format(x,'b')

'10011010010'

In [25]:
format(x,'o')

'2322'

In [29]:
format(x,'x')

'4d2'

为了以不同的进制转换整数字符串，简单的使用带有进制的int() 函数即可：

In [30]:
int('4d2',16)

1234

## 3.5 字节到大整数的打包与解包

In [31]:
data = b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

In [33]:
int.from_bytes(data,'big')

94522842520747284487117727783387188

In [34]:
x = 94522842520747284487117727783387188

In [36]:
x.to_bytes(16,'big')

b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

## 3.6 复数的数学运算

In [37]:
a = complex(2,3)

In [38]:
a

(2+3j)

In [39]:
b = 2+5j

In [41]:
b

(2+5j)

In [42]:
b.real,b.imag

(2.0, 5.0)

In [43]:
import cmath

In [44]:
cmath.sin(b)

(67.47891523845588-30.879431343588244j)

In [45]:
cmath.sqrt(-1)

1j

In [46]:
import math

In [47]:
math.sqrt(-1)

ValueError: math domain error

## 3.7 无穷大与NaN

In [48]:
a = float('inf')

In [49]:
math.isinf(a)

True

In [50]:
a

inf

In [51]:
b = float('nan')
math.isnan(b)

True

## 3.8 分数运算

In [52]:
from fractions import Fraction

In [53]:
a = Fraction(1,3)

In [60]:
b = Fraction(3,5)

In [61]:
c = a*b

In [62]:
c.numerator

1

In [63]:
float(c)

0.2

## 3.9 大型数组运算

<b>我们采用numpy库来进行数学计算</b>

In [67]:
import numpy as np

In [68]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [69]:
a[1]

array([5, 6, 7, 8])

In [70]:
a[:,1]

array([ 2,  6, 10])

In [71]:
a[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
a[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [73]:
np.where(a < 10, a, 10)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 10, 10]])

## 3.10 矩阵与线性代数运算

In [74]:
m = np.matrix([[1,-2,3],[0,4,5],[7,8,-9]])

In [75]:
m

matrix([[ 1, -2,  3],
        [ 0,  4,  5],
        [ 7,  8, -9]])

In [76]:
m.T

matrix([[ 1,  0,  7],
        [-2,  4,  8],
        [ 3,  5, -9]])

In [77]:
m.I

matrix([[ 0.33043478, -0.02608696,  0.09565217],
        [-0.15217391,  0.13043478,  0.02173913],
        [ 0.12173913,  0.09565217, -0.0173913 ]])

In [78]:
v = np.matrix([[2],[3],[4]])

In [81]:
from numpy.linalg import solve

In [82]:
x = solve(m,v)

In [83]:
m * x

matrix([[ 2.],
        [ 3.],
        [ 4.]])

In [84]:
x

matrix([[ 0.96521739],
        [ 0.17391304],
        [ 0.46086957]])

## 3.11 随机选择

In [85]:
import random
values = [1, 2, 3, 4, 5, 6]

In [86]:
random.choice(values)

3

In [91]:
random.sample(values,3)

[3, 1, 6]

In [92]:
random.shuffle(values)

In [93]:
values

[2, 4, 6, 1, 5, 3]

## 3.12 基本的日期与时间转换

In [94]:
from datetime import timedelta

In [95]:
a = timedelta(days=2,hours=5)

In [96]:
a

datetime.timedelta(2, 18000)

In [97]:
a.days

2

In [99]:
from datetime import datetime
a = datetime(2012,3,1)
b = datetime(2012,2,28)
a - b

datetime.timedelta(2)

## 3.13 计算最后一个周五的日期

In [100]:
datetime.now()

datetime.datetime(2017, 1, 8, 14, 30, 51, 253740)

## 3.15 字符串转换为日期

In [101]:
text = '2012-09-20'

In [102]:
datetime.strptime(text,'%Y-%m-%d')

datetime.datetime(2012, 9, 20, 0, 0)

### 在这一章中，我们学习了简单的日期数字操作